export const MAX_DATE_MILLISECONDS = 8640000000000000;

export const MILLISECONDS_IN_MINUTE = 60000;
export const MILLISECONDS_IN_HOUR = MILLISECONDS_IN_MINUTE * 60;
export const MILLISECONDS_IN_DAY = MILLISECONDS_IN_HOUR * 24;
export const MILLISECONDS_IN_WEEK = MILLISECONDS_IN_DAY * 7;
export const MILLISECONDS_IN_YEAR = 31536000000;
export const MILLISECONDS_IN_DECADE = MILLISECONDS_IN_YEAR * 10;
